# Generated by Django 3.0.3 on 2020-02-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='name',
        ),
    ]
