# Generated by Django 3.0.3 on 2020-02-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0002_auto_20200226_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='unit',
        ),
    ]
