# Generated by Django 3.0.3 on 2020-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200303_0848'),
        ('chemmanager', '0002_auto_20200302_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='group',
        ),
        migrations.AddField(
            model_name='chemical',
            name='workgroup',
            field=models.ManyToManyField(to='users.Workgroup'),
        ),
        migrations.AddField(
            model_name='storage',
            name='workgroup',
            field=models.ManyToManyField(to='users.Workgroup'),
        ),
    ]
