# Generated by Django 3.0.3 on 2020-03-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200303_0848'),
        ('chemmanager', '0003_auto_20200303_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='workgroup',
        ),
        migrations.AddField(
            model_name='chemical',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Workgroup'),
        ),
    ]
