# Generated by Django 3.0.4 on 2020-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0003_auto_20200306_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chemical_pics'),
        ),
    ]
