# Generated by Django 3.0.3 on 2020-03-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0004_auto_20200303_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='chemical_pics'),
        ),
    ]
