# Generated by Django 3.0.3 on 2020-02-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0004_auto_20200226_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='equals_si',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
