# Generated by Django 3.0.3 on 2020-03-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0005_chemical_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='structure',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
