# Generated by Django 3.0.3 on 2020-02-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0005_unit_equals_si'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='name',
        ),
        migrations.AddField(
            model_name='unit',
            name='equals_si_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chemmanager.Unit'),
        ),
    ]
