# Generated by Django 3.0.4 on 2020-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0005_storage_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='equals_standard',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
