# Generated by Django 3.0.4 on 2020-03-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0006_auto_20200307_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chemmanager.Unit'),
            preserve_default=False,
        ),
    ]
