# Generated by Django 3.0.3 on 2020-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0006_auto_20200303_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='image',
            field=models.ImageField(default='chemical_pics/default.png', upload_to='chemical_pics'),
        ),
    ]
