# Generated by Django 3.0.3 on 2020-02-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0006_auto_20200226_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='equals_si',
            new_name='equals_standard',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='equals_si_unit',
            new_name='equals_standard_unit',
        ),
    ]
