# Generated by Django 3.0.3 on 2020-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0007_auto_20200303_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chemical_pics'),
        ),
    ]
