# Generated by Django 3.0.3 on 2020-02-26 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0007_auto_20200226_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='date_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
