# Generated by Django 3.0.4 on 2020-03-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0008_auto_20200308_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
