# Generated by Django 3.0.3 on 2020-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0008_auto_20200226_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
