# Generated by Django 3.0.3 on 2020-02-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0010_extraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='chemical',
        ),
        migrations.AddField(
            model_name='extraction',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chemmanager.Stock'),
            preserve_default=False,
        ),
    ]
