# Generated by Django 3.0.3 on 2020-02-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemmanager', '0011_auto_20200227_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chemmanager.Unit'),
            preserve_default=False,
        ),
    ]
