# Generated by Django 3.0.3 on 2020-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('chemmanager', '0012_extraction_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraction',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_changed']},
        ),
        migrations.AddField(
            model_name='chemical',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
