name: Run Django Tests

on:
  push:
  pull_request:

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run Django Tests
        run: |
          python manage.py test